#!/usr/bin/env node
// canonical source: vanilla-web/previews/new.mjs@b6958a9 — vendored copy, do not edit here
// @ts-check
// Scaffolds a starter <name>.preview.js for one component (see reference/preview.md).
// This is a one-time SEED, not generated output: it writes the boilerplate
// (imports, the @type path, the render adapter, title) plus one TODO variant, and
// refuses to overwrite an existing file. You fill in the variants. It's a separate
// step IN FRONT of the code generator — run previews/scan.mjs (or just start
// serve.mjs) afterward to catalogue the new preview.
//
//   node previews/new.mjs <component>      # e.g. node previews/new.mjs stat-card

import { stat, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const name = process.argv[2];
if (!name) {
  console.error("usage: node previews/new.mjs <component>");
  process.exit(1);
}

const root = dirname(dirname(fileURLToPath(import.meta.url))); // web/ — parent of previews/
const dir = join(root, "components", name);
const factory = join(dir, `${name}.js`);
const target = join(dir, `${name}.preview.js`);

/** @param {string} p */
const exists = async (p) => !!(await stat(p).catch(() => null));

if (!(await exists(dir))) {
  console.error(`no such component: components/${name}/ (create the component first)`);
  process.exit(1);
}
if (!(await exists(factory))) {
  console.error(`missing factory: components/${name}/${name}.js`);
  process.exit(1);
}
if (await exists(target)) {
  console.error(`already exists: components/${name}/${name}.preview.js (refusing to overwrite)`);
  process.exit(1);
}

// stat-card → StatCard → createStatCard (the create<Name> factory contract).
// Generated by convention; if the real names differ, the tsc gate flags it and
// you fix the seed — the scaffolder stays dumb (no source parsing).
const pascal = name.replace(/(^|[-_])([a-z])/g, (_, __, c) => c.toUpperCase());
const create = `create${pascal}`;

const body =
  `// @ts-check\n` +
  `import { ${create} } from "./${name}.js";\n\n` +
  `/** @type {import("../../preview.js").PreviewModule} */\n` +
  `export default {\n` +
  `  title: ${JSON.stringify(name)},\n` +
  `  // Adapts the factory's return to an element. If ${create} returns the\n` +
  `  // element directly (not { el }), drop the .then().\n` +
  `  render: (props, signal) => ${create}(props, signal).then((c) => c.el),\n` +
  `  variants: {\n` +
  `    default: {\n` +
  `      // TODO: props for ${create}(...) — see its @param\n` +
  `    },\n` +
  `  },\n` +
  `};\n`;

await writeFile(target, body);
console.log(`created components/${name}/${name}.preview.js — fill in variants, then run previews/scan.mjs`);
