// @ts-check
// GENERATED by previews/scan.mjs — do not edit by hand.
// Regenerated on `node serve.mjs` startup; commit it alongside the component.
/** @typedef {{ title: string, dir: string, load: () => Promise<{ default: any }> }} PreviewEntry */
/** @type {PreviewEntry[]} */
export const previews = [
  { title: "alert", dir: "components/alert", load: () => import("../components/alert/alert.preview.js") },
  { title: "app-bar", dir: "components/app-bar", load: () => import("../components/app-bar/app-bar.preview.js") },
  { title: "avatar", dir: "components/avatar", load: () => import("../components/avatar/avatar.preview.js") },
  { title: "button", dir: "components/button", load: () => import("../components/button/button.preview.js") },
  { title: "checklist-row", dir: "components/checklist-row", load: () => import("../components/checklist-row/checklist-row.preview.js") },
  { title: "chip", dir: "components/chip", load: () => import("../components/chip/chip.preview.js") },
  { title: "code-input", dir: "components/code-input", load: () => import("../components/code-input/code-input.preview.js") },
  { title: "dialog", dir: "components/dialog", load: () => import("../components/dialog/dialog.preview.js") },
  { title: "empty-state", dir: "components/empty-state", load: () => import("../components/empty-state/empty-state.preview.js") },
  { title: "field", dir: "components/field", load: () => import("../components/field/field.preview.js") },
  { title: "kv-row", dir: "components/kv-row", load: () => import("../components/kv-row/kv-row.preview.js") },
  { title: "list-row", dir: "components/list-row", load: () => import("../components/list-row/list-row.preview.js") },
  { title: "menu", dir: "components/menu", load: () => import("../components/menu/menu.preview.js") },
  { title: "panel", dir: "components/panel", load: () => import("../components/panel/panel.preview.js") },
  { title: "progress", dir: "components/progress", load: () => import("../components/progress/progress.preview.js") },
  { title: "scroll-stack", dir: "components/scroll-stack", load: () => import("../components/scroll-stack/scroll-stack.preview.js") },
  { title: "segmented-control", dir: "components/segmented-control", load: () => import("../components/segmented-control/segmented-control.preview.js") },
  { title: "side-nav", dir: "components/side-nav", load: () => import("../components/side-nav/side-nav.preview.js") },
  { title: "skeleton", dir: "components/skeleton", load: () => import("../components/skeleton/skeleton.preview.js") },
  { title: "spinner", dir: "components/spinner", load: () => import("../components/spinner/spinner.preview.js") },
  { title: "stat-card", dir: "components/stat-card", load: () => import("../components/stat-card/stat-card.preview.js") },
  { title: "status-dot", dir: "components/status-dot", load: () => import("../components/status-dot/status-dot.preview.js") },
  { title: "table-shell", dir: "components/table-shell", load: () => import("../components/table-shell/table-shell.preview.js") },
  { title: "tooltip", dir: "components/tooltip", load: () => import("../components/tooltip/tooltip.preview.js") },
  { title: "view-header", dir: "components/view-header", load: () => import("../components/view-header/view-header.preview.js") },
];
