// @ts-check
// GENERATED by previews/scan.mjs — do not edit by hand.
// Regenerated on `node serve.mjs` startup; commit it alongside the component.
/** @typedef {{ title: string, load: () => Promise<{ default: any }> }} PreviewEntry */
/** @type {PreviewEntry[]} */
export const previews = [
  { title: "chip", load: () => import("../components/chip/chip.preview.js") },
  { title: "panel", load: () => import("../components/panel/panel.preview.js") },
  { title: "stat-card", load: () => import("../components/stat-card/stat-card.preview.js") },
  { title: "status-dot", load: () => import("../components/status-dot/status-dot.preview.js") },
  { title: "tooltip", load: () => import("../components/tooltip/tooltip.preview.js") },
];
