#!/usr/bin/env node
// canonical source: vanilla-web/previews/scan.mjs@57e897c — vendored copy, do not edit here
// @ts-check
// Generates previews/registry.js by walking components/ for *.preview.js files.
// This is the no-build equivalent of a bundler's glob (or a C# source generator):
// the browser has no reflection and can't enumerate files, so something with
// filesystem access has to emit the import list. See reference/preview.md.
//
//   node previews/scan.mjs        # regenerate by hand
//   (serve.mjs also calls this on startup, so a new *.preview.js is picked up
//    next time you start the dev server — no manual step in the common case)
//
// Title comes from the component folder name (pure path work — a preview module
// is never executed here, so a broken preview can't break discovery). The output
// is committed and only changes when the SET of preview files changes, so there's
// no git churn on ordinary edits.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname, basename, relative } from "node:path";
import { fileURLToPath } from "node:url";

/** Recursively collect every *.preview.js under `dir` (missing dir → []).
 * @param {string} dir
 * @returns {Promise<string[]>} */
async function walk(dir) {
  /** @type {string[]} */
  const out = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return out; // no such dir → nothing to scan
  }
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(p)));
    else if (e.name.endsWith(".preview.js")) out.push(p);
  }
  return out;
}

/** Scan `<webRoot>/components` and (re)write `<webRoot>/previews/registry.js`.
 * Writes only when the content changed, to avoid needless mtime/git churn.
 * @param {string} [webRoot] defaults to the parent of this file's dir
 * @returns {Promise<number>} number of component previews found */
export default async function scanPreviews(webRoot) {
  const here = dirname(fileURLToPath(import.meta.url));
  const root = webRoot || dirname(here); // web/ — the parent of previews/
  const previewsDir = join(root, "previews");

  const files = (await walk(join(root, "components"))).sort();
  const entries = files.map((f) => {
    const compDir = dirname(f);
    const rel = relative(previewsDir, f).split("\\").join("/");
    return {
      title: basename(compDir), // component folder name
      importPath: rel.startsWith(".") ? rel : "./" + rel, // keep a valid ESM specifier
      // web-root-relative, so the harness can fetch() <dir>/<title>.{html,css,js}
      // straight from the served page — see reference/preview.md → view source.
      dir: relative(root, compDir).split("\\").join("/"),
    };
  });

  const body =
    `// @ts-check\n` +
    `// GENERATED by previews/scan.mjs — do not edit by hand.\n` +
    `// Regenerated on \`node serve.mjs\` startup; commit it alongside the component.\n` +
    `/** @typedef {{ title: string, dir: string, load: () => Promise<{ default: any }> }} PreviewEntry */\n` +
    `/** @type {PreviewEntry[]} */\n` +
    `export const previews = [\n` +
    entries
      .map((e) => `  { title: ${JSON.stringify(e.title)}, dir: ${JSON.stringify(e.dir)}, load: () => import(${JSON.stringify(e.importPath)}) },`)
      .join("\n") +
    (entries.length ? "\n" : "") +
    `];\n`;

  const target = join(previewsDir, "registry.js");
  const prev = await readFile(target, "utf8").catch(() => "");
  if (prev !== body) await writeFile(target, body);
  return entries.length;
}

// Invoked directly (node previews/scan.mjs) → run and report.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const n = await scanPreviews();
  console.log(`previews/registry.js: ${n} component preview(s)`);
}
