// GENERATED by bridge/gen-previews.mjs from alert.preview.js — do not edit by hand.
import { Alert } from "vanilla-components";

export const Neutral = () => <Alert message={"Draft saved."} />;

export const Info = () => <Alert tone={"info"} title={"Heads up"} message={"A new version is available."} />;

export const Warn = () => <Alert tone={"warn"} message={"Your session expires in 5 minutes."} />;

export const Bad = () => <Alert tone={"bad"} title={"Couldn't save"} message={"Check your connection and try again."} dismissible />;

export const Custom = () => <Alert tone={"#8b5cf6"} message={"A custom-toned notice."} />;
