// GENERATED by bridge/gen-previews.mjs from avatar.preview.js — do not edit by hand.
import { Avatar } from "vanilla-components";

export const Initials = () => <Avatar name={"Ada Lovelace"} />;

export const Image = () => <Avatar src={"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='64' height='64'><rect width='64' height='64' fill='%238ab4f8'/><text x='32' y='42' font-size='30' text-anchor='middle' fill='white'>A</text></svg>"} name={"Ada Lovelace"} />;

export const Toned = () => <Avatar name={"Kurt Gödel"} tone={"info"} size={40} />;

export const Custom = () => <Avatar initials={"7"} tone={"#8b5cf6"} size={48} />;
