// GENERATED by bridge/gen-previews.mjs from button.preview.js — do not edit by hand.
import { Button } from "vanilla-components";

export const Default = () => <Button label={"Cancel"} />;

export const Primary = () => <Button label={"Generate"} variant={"primary"} />;

export const Danger = () => <Button label={"Delete"} variant={"danger"} />;

export const Ghost = () => <Button label={"Dismiss"} variant={"ghost"} />;

export const Small = () => <Button label={"Open"} size={"sm"} />;

export const Link = () => <Button label={"Open repo"} icon={"↗"} href={"https://example.com"} target={"_blank"} variant={"ghost"} />;

export const Pressed = () => <Button label={"Live"} pressed />;
