// GENERATED by bridge/gen-previews.mjs from checklist-row.preview.js — do not edit by hand.
import { ChecklistRow } from "vanilla-components";

export const Done = () => <ChecklistRow text={"Wire up the type gate"} done />;

export const Todo = () => <ChecklistRow text={"Render-check design-sync"} done={false} />;
