// GENERATED by bridge/gen-previews.mjs from chip.preview.js — do not edit by hand.
import { Chip } from "vanilla-components";

export const Neutral = () => <Chip text={"draft"} />;

export const Ready = () => <Chip text={"ready"} tone={"ok"} dot />;

export const Degraded = () => <Chip text={"degraded"} tone={"warn"} dot />;

export const Failed = () => <Chip text={"failed"} tone={"bad"} dot />;

export const Live = () => <Chip text={"12 live"} tone={"info"} />;

export const Branded = () => <Chip text={"v4.2"} tone={"#8b5cf6"} />;
