// GENERATED by bridge/gen-previews.mjs from code-input.preview.js — do not edit by hand.
import { CodeInput } from "vanilla-components";

export const SixDigit = () => <CodeInput length={6} />;

export const FourDigit = () => <CodeInput length={4} />;

export const Alphanumeric = () => <CodeInput length={5} type={"text"} />;
