// GENERATED by bridge/gen-previews.mjs from dialog.preview.js — do not edit by hand.
import { Dialog } from "vanilla-components";

export const Confirm = () => <Dialog title={"Reset the world?"} body={"This clears all parcels and re-bootstraps from the chronicle. It cannot be undone."} />;

export const Scrolling = () => <Dialog title={"Release notes"} body={"Line one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\nLine one.\n"} scroll closeOnBackdrop />;
