// GENERATED by bridge/gen-previews.mjs from field.preview.js — do not edit by hand.
import { Field } from "vanilla-components";

export const Text = () => <Field label={"Session name"} value={"morning standup"} placeholder={"name this session"} />;

export const Select = () => <Field label={"Backend"} type={"select"} value={"whisper"} options={[{"value":"whisper","label":"Whisper"},{"value":"canary","label":"Canary"},{"value":"auto","label":"Auto"}]} />;

export const Textarea = () => <Field label={"Hotwords"} type={"textarea"} value={"Verktøykasse\nSlipestein"} hint={"one per line"} />;

export const Toolbar = () => <Field label={"Filter"} type={"search"} placeholder={"filter…"} hideLabel />;
