// GENERATED by bridge/gen-previews.mjs from kv-row.preview.js — do not edit by hand.
import { KvRow } from "vanilla-components";

export const Plain = () => <KvRow label={"Decode rate"} value={"142 tok/s"} />;

export const Ok = () => <KvRow label={"Status"} value={"healthy"} tone={"ok"} />;

export const Bad = () => <KvRow label={"Errors"} value={3} tone={"bad"} />;
