// GENERATED by bridge/gen-previews.mjs from list-row.preview.js — do not edit by hand.
import { ListRow } from "vanilla-components";

export const Basic = () => <ListRow title={"Bergen"} meta={"3 races logged"} />;

export const LeadingTrailing = () => <ListRow leading={"🏔"} title={"Trondheim"} meta={"5 races"} trailing={"→"} />;

export const Link = () => <ListRow title={"Oslo"} meta={"12 races"} href={"#/oslo"} trailing={"→"} />;
