// GENERATED by bridge/gen-previews.mjs from menu.preview.js — do not edit by hand.
import { Menu } from "vanilla-components";

export const Actions = () => <Menu items={[{"id":"edit","label":"Edit","icon":"✎"},{"id":"duplicate","label":"Duplicate"},"separator",{"id":"delete","label":"Delete","icon":"🗑","danger":true}]} />;

export const WithDisabled = () => <Menu items={[{"id":"open","label":"Open"},{"id":"archive","label":"Archive","disabled":true},{"id":"share","label":"Share"}]} />;
