// GENERATED by bridge/gen-previews.mjs from panel.preview.js — do not edit by hand.
import { Panel } from "vanilla-components";

export const Titled = () => <Panel head={"Sessions"} body={"12 active · 3 recording"} />;

export const Headless = () => <Panel body={"A bare panel — just a body, no header."} />;

export const Fill = () => <Panel head={"Console"} body={"fill:true stretches in a flex column and scrolls its body"} />;
