// GENERATED by bridge/gen-previews.mjs from progress.preview.js — do not edit by hand.
import { Progress } from "vanilla-components";

export const Labeled = () => <Progress value={64} label={"Transcribing… 64%"} />;

export const Ok = () => <Progress value={100} tone={"ok"} />;

export const Warn = () => <Progress value={38} tone={"warn"} />;

export const Bad = () => <Progress value={12} tone={"bad"} />;
