// GENERATED by bridge/gen-previews.mjs from segmented-control.preview.js — do not edit by hand.
import { SegmentedControl } from "vanilla-components";

export const Source = () => <SegmentedControl options={[{"id":"original","label":"Original"},{"id":"stripped","label":"Stripped"}]} current={"original"} />;

export const Summary = () => <SegmentedControl options={[{"id":"merged","label":"Merged"},{"id":"speaker","label":"Per-speaker"},{"id":"raw","label":"Raw"}]} current={"speaker"} />;

export const PerOptionTone = () => <SegmentedControl options={[{"id":"all","label":"All"},{"id":"ok","label":"Passing","tone":"ok"},{"id":"bad","label":"Failing","tone":"bad"}]} current={"ok"} />;
