// GENERATED by bridge/gen-previews.mjs from skeleton.preview.js — do not edit by hand.
import { Skeleton } from "vanilla-components";

export const Text = () => <Skeleton variant={"text"} lines={3} width={240} />;

export const Block = () => <Skeleton variant={"block"} width={240} height={120} />;

export const Circle = () => <Skeleton variant={"circle"} width={48} />;
