// GENERATED by bridge/gen-previews.mjs from spinner.preview.js — do not edit by hand.
import { Spinner } from "vanilla-components";

export const Small = () => <Spinner size={14} />;

export const Labeled = () => <Spinner size={18} label={"Loading…"} />;

export const Large = () => <Spinner size={32} />;
