// GENERATED by bridge/gen-previews.mjs from status-dot.preview.js — do not edit by hand.
import { StatusDot } from "vanilla-components";

export const Live = () => <StatusDot tone={"ok"} pulse label={"live"} />;

export const Recording = () => <StatusDot tone={"bad"} pulse label={"recording"} />;

export const Lagging = () => <StatusDot tone={"warn"} label={"lagging"} />;

export const Idle = () => <StatusDot label={"idle"} />;
