// GENERATED by bridge/gen-previews.mjs from table-shell.preview.js — do not edit by hand.
import { TableShell } from "vanilla-components";

export const Scorecard = () => <TableShell caption={"Recent runs"} columns={[{"key":"date","label":"Date"},{"key":"task","label":"Task"},{"key":"score","label":"Score","align":"end"}]} rows={[["2026-06-14","Refactor parser",92],["2026-06-15","Add type gate",88],["2026-06-16","Wire design-sync",95]]} />;

export const Pairs = () => <TableShell columns={[{"key":"key","label":"Setting"},{"key":"value","label":"Value","align":"end"}]} rows={[["Workers",4],["Timeout","30s"]]} />;
