// GENERATED by bridge/gen-previews.mjs from tooltip.preview.js — do not edit by hand.
import { Tooltip } from "vanilla-components";

export const Text = () => <Tooltip content={"Builds the landscape from your commit history."} />;

export const Short = () => <Tooltip content={"Copy"} />;
