// GENERATED by bridge/gen-previews.mjs from view-header.preview.js — do not edit by hand.
import { ViewHeader } from "vanilla-components";

export const Full = () => <ViewHeader eyebrow={"Stages"} title={"Capture"} sub={"live transcription from active taps"} />;

export const Plain = () => <ViewHeader title={"Overview"} />;

export const Dense = () => <ViewHeader eyebrow={"Service"} title={"registry-agent"} sub={"thinker"} dense />;
