// @ts-check
// GENERATED by previews/scan.mjs — do not edit by hand.
// Regenerated on `node serve.mjs` startup; commit it alongside the component.
/** @typedef {{ title: string, load: () => Promise<{ default: any }> }} PreviewEntry */
/** @type {PreviewEntry[]} */
export const previews = [
];
